Repository prathimacode-hub/IoT-Spot, pull requests merged in 2022-10, with the labels that each got.

#289 Improvement in accomplishment section
  index.html
Labels: Approved, SSOC, Beginner, Web

#276 Fixed X scroll (issue #273)
  IoT-Spot Website/assets/css/style.css
Labels: Fix the Changes

#331 Updating ReadMe of ESP32 folder with information
  ESP32/README.md
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED, Approved

#333 ESP32 GPIO control using Bluetooth
  ESP32/Bluetooth GPIO Control with ESP32/Bluetooth_GPIO_Control_with_ESP32/Bluetooth_GPIO_Control_with_ESP32.ino
  ESP32/Bluetooth GPIO Control with ESP32/Images/OFF.webp
  ESP32/Bluetooth GPIO Control with ESP32/Images/ON.webp
  ESP32/Bluetooth GPIO Control with ESP32/Images/circuit2-768x898.webp
  ESP32/Bluetooth GPIO Control with ESP32/README.md
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED, Approved

#339 Esp8266info
  ESP8266/README.md
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED, Approved
