Repository prathimacode-hub/IoT-Spot, pull requests merged in 2022-05, with the labels that each got.

#225 204 improve button and hover
  assets/css/style.css
  index.html
Labels: Approved, GSSoC22, Level0

#213 Scroll bar added
  assets/css/style.css
Labels: Approved, GSSoC22, Level0

#230 Motion Controlled Color Changer added
  Minor Scripts/Arduino/Motion Controlled Color Changer/Images/motion_controlled_color_changer.mp4
  Minor Scripts/Arduino/Motion Controlled Color Changer/Images/motion_controlled_color_changer.png
  Minor Scripts/Arduino/Motion Controlled Color Changer/README.md
  Minor Scripts/Arduino/Motion Controlled Color Changer/motion_controlled_color_changer.ino
  Minor Scripts/Arduino/Motion Controlled Color Changer/requirements.txt
Labels: Level1, Approved, GSSoC22

#242 Blog Section Updated
  assets/blog.html
  assets/css/blog.css
Labels: Level1, Approved, GSSoC22

#248 Simon Says Game added
  Minor Scripts/Arduino/Simon Says Game/Images/simon_says_game.mp4
  Minor Scripts/Arduino/Simon Says Game/Images/simon_says_game.png
  Minor Scripts/Arduino/Simon Says Game/README.md
  Minor Scripts/Arduino/Simon Says Game/requirements.txt
  Minor Scripts/Arduino/Simon Says Game/simon_says_game.ino
Labels: Level2, Approved, GSSoC22

#243 LCD interfacing with Atmega32
  Atmel/LCD_Interface_with_atmega32/Code/.vs/LCD_Driver/v14/.atsuo
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver.atsln
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Bit_Math.h
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/DIO_CONFIG.h
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/DIO_INT.h
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/DIO_PRG.c
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/DIO_REG.h
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/DIO_PRG.d
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/DIO_PRG.o
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/LCD_Driver.eep
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/LCD_Driver.elf
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/LCD_Driver.hex
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/LCD_Driver.lss
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/LCD_Driver.map
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/LCD_Driver.srec
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/LCD_PRG.d
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/LCD_PRG.o
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/Makefile
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/main.d
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/main.o
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/Debug/makedep.mk
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/LCD_CONFIG.h
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/LCD_Driver.componentinfo.xml
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/LCD_Driver.cproj
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/LCD_INT.h
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/LCD_PRG.c
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/delay.h
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/main.c
  Atmel/LCD_Interface_with_atmega32/Code/LCD_Driver/std_types.h
  Atmel/LCD_Interface_with_atmega32/Gallery/Video.mp4
  Atmel/LCD_Interface_with_atmega32/Gallery/after running.PNG
  Atmel/LCD_Interface_with_atmega32/Gallery/berfore run.PNG
  Atmel/LCD_Interface_with_atmega32/README.md
  Atmel/LCD_Interface_with_atmega32/simulation/Backup Of simulation.pdsbak
  Atmel/LCD_Interface_with_atmega32/simulation/Last Loaded simulation.fv8.5.pdsbak
  Atmel/LCD_Interface_with_atmega32/simulation/Last Loaded simulation.pdsbak
  Atmel/LCD_Interface_with_atmega32/simulation/simulation.pdsprj
  Atmel/LCD_Interface_with_atmega32/simulation/simulation.pdsprj.MOHAMEDISMAIL.hp.workspace
Labels: Level2, Approved, GSSoC22

#251 Solve the problem of stack of image and content
  IoT-Spot Website/assets/css/style.css
Labels: Level1, Approved, GSSoC22

#236 Automatic Doorbell
  Minor Scripts/Arduino/Automatic Door Bell/Images/preview.mp4
  Minor Scripts/Arduino/Automatic Door Bell/Images/preview1.jpg
  Minor Scripts/Arduino/Automatic Door Bell/README.md
  Minor Scripts/Arduino/Automatic Door Bell/door_bell.ino
Labels: Level1, Approved, GSSoC22

#258 Improved the CSS part of navigation tabs, contact page and buttons.
  IoT-Spot Website/assets/css/style.css
Labels: Level1, Approved, GSSoC22

#256 Display Time in LCD
  Raspberry Pi/Display-Time-in-LCD/README.md
  Raspberry Pi/Display-Time-in-LCD/requirements.txt
  Raspberry Pi/Display-Time-in-LCD/time.py
Labels: Level1, Approved, GSSoC22
