Repository prathimacode-hub/IoT-Spot, pull requests merged in 2022-03, with the labels that each got.

#61 Led Brightness Control using Arduino
  Arduino/LED Brightness Control/Gallery/Brightness-Control-2022-03-02_00.51.49.mp4
  Arduino/LED Brightness Control/Gallery/Led-Brightness-Control1.png
  Arduino/LED Brightness Control/Gallery/Led-Brightness-control.png
  Arduino/LED Brightness Control/Led_Brightness_Control.ino
  Arduino/LED Brightness Control/README.md
Labels: Level 1, Approved, GSSoC22

#71 Fixed social icons alignment in contact us section
  assets/css/style.css
Labels: Approved, GSSoC22

#75 Basic led blinking using arduino
  Arduino/Basic LED Blinking Using Arduino/Basic_LED_Blinking_using_Arduino.ino
  Arduino/Basic LED Blinking Using Arduino/Images/Basic_LED_Blinking_Using_Arduino_Simulation.mp4
  Arduino/Basic LED Blinking Using Arduino/Images/Fritzing Circuit Diagram.png
  Arduino/Basic LED Blinking Using Arduino/README.md
  Arduino/Humidity Sensing Using Arduino/Humidity_Sensing_Using_Arduino.ino
Labels: Level 1, Approved, GSSoC22

#92 Soil Moisture using Arduino
  Minor Scripts/Arduino/Soil Moisture using Arduino/Images/SS-1.png
  Minor Scripts/Arduino/Soil Moisture using Arduino/Images/SS-2.png
  Minor Scripts/Arduino/Soil Moisture using Arduino/Images/SS-3.png
  Minor Scripts/Arduino/Soil Moisture using Arduino/Images/SS-4.png
  Minor Scripts/Arduino/Soil Moisture using Arduino/Images/SS-5.png
  Minor Scripts/Arduino/Soil Moisture using Arduino/Images/Soil Moisture Video Demonstration.mp4
  Minor Scripts/Arduino/Soil Moisture using Arduino/README.md
  Minor Scripts/Arduino/Soil Moisture using Arduino/Soil_Moisture_Code.cpp.cpp
  Minor Scripts/Arduino/Soil Moisture using Arduino/requirements.txt
Labels: Level 2, Approved, GSSoC22

#99 Humidity Sensing using Arduino
  Minor Scripts/Arduino/Humidity Sensing using Arduino/Humidity_Sensing_Code.cpp.cpp
  Minor Scripts/Arduino/Humidity Sensing using Arduino/Images/Humidity Sensing Video Demonstration.mp4
  Minor Scripts/Arduino/Humidity Sensing using Arduino/Images/SS-1.png
  Minor Scripts/Arduino/Humidity Sensing using Arduino/Images/SS-2.png
  Minor Scripts/Arduino/Humidity Sensing using Arduino/Images/SS-3.png
  Minor Scripts/Arduino/Humidity Sensing using Arduino/Images/SS-4.png
  Minor Scripts/Arduino/Humidity Sensing using Arduino/Images/SS-5.png
  Minor Scripts/Arduino/Humidity Sensing using Arduino/README.md
  Minor Scripts/Arduino/Humidity Sensing using Arduino/requirements.txt
Labels: Level 2, Approved, GSSoC22

#100 Automated Hand Sanitizer Dispenser
  Minor Scripts/Arduino/Automated Hand Sanitizer Dispenser/Automated_Hand_Sanitizer_Dispenser.cpp.cpp
  Minor Scripts/Arduino/Automated Hand Sanitizer Dispenser/Images/Automated Hand Sanitizer Dispenser Video Demonstration.mp4
  Minor Scripts/Arduino/Automated Hand Sanitizer Dispenser/Images/SS-1.png
  Minor Scripts/Arduino/Automated Hand Sanitizer Dispenser/Images/SS-2.png
  Minor Scripts/Arduino/Automated Hand Sanitizer Dispenser/Images/SS-3.png
  Minor Scripts/Arduino/Automated Hand Sanitizer Dispenser/README.md
  Minor Scripts/Arduino/Automated Hand Sanitizer Dispenser/requirements.txt
Labels: Level 2, Approved, GSSoC22

#79 Humidity Sensing using arduino
  Arduino/Humidity Sensing Using Arduino/Humidity_Sensing_Using_Arduino.ino
  Arduino/Humidity Sensing Using Arduino/Images/Fritzing Circuit Diagram.png
  Arduino/Humidity Sensing Using Arduino/Images/Humidity_Sensing_Using_Arduino_Simulation.mp4
  Arduino/Humidity Sensing Using Arduino/README.md
Labels: Level 1, Approved, GSSoC22

#109 Voltage Sensing using Arduino
  Arduino/Voltage Sensing using Arduino/Images/SS-1.png
  Arduino/Voltage Sensing using Arduino/Images/SS-2.png
  Arduino/Voltage Sensing using Arduino/Images/SS-3.png
  Arduino/Voltage Sensing using Arduino/Images/Voltage Sensing using Arduino Video Demonstration.mp4
  Arduino/Voltage Sensing using Arduino/README.md
  Arduino/Voltage Sensing using Arduino/Voltage Sensing using Arduino.cpp.cpp
  Arduino/Voltage Sensing using Arduino/requirements.txt
Labels: Level 1, Fix the Changes, GSSoC22

#115 Added blog page
  assets/blog.html
  assets/css/blog.css
  assets/images/Card_img.jpg
  index.html
Labels: Level 2, Approved, GSSoC22

#116 HOME AUTOMATION
  Minor Scripts/Arduino/Home Automation/Images/home_automation.JPG
  Minor Scripts/Arduino/Home Automation/Images/home_automation.mp4
  Minor Scripts/Arduino/Home Automation/README.md
  Minor Scripts/Arduino/Home Automation/home_automation.cpp
  Minor Scripts/Arduino/Home Automation/requirements.txt
Labels: Level 2, Approved, GSSoC22

#119 Fire Alarm using Arduino
  Minor Scripts/Arduino/Fire Alarm using Arduino/Fire Alarm using Arduino.cpp.cpp
  Minor Scripts/Arduino/Fire Alarm using Arduino/Images/Fire Alarm using Arduino Video Demonstration.mp4
  Minor Scripts/Arduino/Fire Alarm using Arduino/Images/SS-1.png
  Minor Scripts/Arduino/Fire Alarm using Arduino/Images/SS-2.png
  Minor Scripts/Arduino/Fire Alarm using Arduino/Images/SS-3.png
  Minor Scripts/Arduino/Fire Alarm using Arduino/Images/SS-4.png
  Minor Scripts/Arduino/Fire Alarm using Arduino/README.md
  Minor Scripts/Arduino/Fire Alarm using Arduino/requirements.txt
Labels: Level 1, Approved, GSSoC22

#98 DC Motor Interfacing using 8051 Microcontroller
  8051/DC Motor Interfacing/DC-motor.hex
  8051/DC Motor Interfacing/Gallery/DCmotor-2022-03-05_17.57.12.mp4
  8051/DC Motor Interfacing/Gallery/dc-motor.PNG
  8051/DC Motor Interfacing/Gallery/dc-motor1.PNG
  8051/DC Motor Interfacing/README.md
  8051/DC Motor Interfacing/dc_motor.c
Labels: Level 1, Approved, GSSoC22

#124 Fixed some Spells and errors
  index.html
Labels: Approved, GSSoC22, Level 0

#94 Update CODE_OF_CONDUCT.md and README.md (Under Arduino Scripts)
  Arduino/README.md
  CODE_OF_CONDUCT.md
Labels: Approved, GSSoC22, Level 0

#101 added tilt effect to main-img
  assets/css/style.css
  assets/js/vanilla-tilt.js
  index.html
Labels: Level 2, Approved, GSSoC22

#135 Stepper Motor Interfacing
  8051/Stepper Motor Interfacing/Gallery/Stepper.PNG
  8051/Stepper Motor Interfacing/Gallery/Stepper_motor-2022-03-17_23.00.56.mp4
  8051/Stepper Motor Interfacing/Gallery/stepper1.PNG
  8051/Stepper Motor Interfacing/README.md
  8051/Stepper Motor Interfacing/requirement.txt
  8051/Stepper Motor Interfacing/stepper.hex
  8051/Stepper Motor Interfacing/stepper_motor.c
Labels: Level1, Approved, GSSoC22

#133 Storing Sensory Data to SD Card
  Arduino/Storing Sensory Data to SD Card/Images/Circuit Diagram.png
  Arduino/Storing Sensory Data to SD Card/Images/Storing_Sensory_Data_to_SD_Card_Simulation.mp4
  Arduino/Storing Sensory Data to SD Card/README.md
  Arduino/Storing Sensory Data to SD Card/Storing_Sensory_Data_to_SD_Card.ino
  Arduino/Storing Sensory Data to SD Card/requirements.txt.txt
Labels: Level1, Approved, GSSoC22

#140 Update style.css
  assets/css/style.css
Labels: Level1, Approved, GSSoC22

#154 #123 Done : Added Dynamic Counter
  index.html
Labels: Level1, Approved, GSSoC22

#153 Added footer in blog page
  assets/blog.html
  assets/css/blog.css
Labels: Level1, Fix the Changes, GSSoC22

#156 Emergency Ventilator
  Minor Scripts/Arduino/Emergency Ventilator/Emergency Ventilator.cpp
  Minor Scripts/Arduino/Emergency Ventilator/Images/Emergency Ventilator Video Demonstration.mp4
  Minor Scripts/Arduino/Emergency Ventilator/Images/SS-1.png
  Minor Scripts/Arduino/Emergency Ventilator/Images/SS-2.png
  Minor Scripts/Arduino/Emergency Ventilator/Images/SS-3.png
  Minor Scripts/Arduino/Emergency Ventilator/Images/SS-4.png
  Minor Scripts/Arduino/Emergency Ventilator/README.md
  Minor Scripts/Arduino/Emergency Ventilator/requirements.txt
Labels: Level2, Approved, GSSoC22

#159 Added hover effect in favicon
  assets/css/style.css
Labels: Level1, GSSoC22

#157 Improved working of button in home page
  index.html
Labels: Approved, GSSoC22, Level0
