Repository prathimacode-hub/IoT-Spot, pull requests merged in 2022-04, with the labels that each got.

#165 GPS Locator Using Arduino
  Minor Scripts/Arduino/GPS Locator/README.md
  Minor Scripts/Arduino/GPS Locator/gps_locator_using_arduino.ino
  Minor Scripts/Arduino/GPS Locator/images/gps_locator_using_arduino.mp4
  Minor Scripts/Arduino/GPS Locator/images/gps_locator_using_arduino.png
  Minor Scripts/Arduino/GPS Locator/requirements.txt
Labels: Level2, Approved, GSSoC22

#168 Ping Pong Game using Arduino
  Minor Scripts/Arduino/Ping Pong Game using Arduino/Images/Circuit Diagram.png
  Minor Scripts/Arduino/Ping Pong Game using Arduino/Images/ping_pong_game_using_arduino_simulation.mp4
  Minor Scripts/Arduino/Ping Pong Game using Arduino/Ping_Pong_Game_Using_Arduino.ino
  Minor Scripts/Arduino/Ping Pong Game using Arduino/README.md
  Minor Scripts/Arduino/Ping Pong Game using Arduino/Requirements.txt
Labels: Level3, Approved, GSSoC22

#179 Solved issue #142 . Made changes in css of scrollbar.
  IoT-Spot Website/assets/css/style.css
  assets/css/style.css
Labels: Approved, GSSoC22, Level0

#178 Mood Ring Light using Arduino
  Minor Scripts/Arduino/Mood Ring Light/Images/mood_ring_light_using_arduino.mp4
  Minor Scripts/Arduino/Mood Ring Light/Images/mood_ring_light_using_arduino.png
  Minor Scripts/Arduino/Mood Ring Light/README.md
  Minor Scripts/Arduino/Mood Ring Light/mood_ring_light_using_arduino.ino
  Minor Scripts/Arduino/Mood Ring Light/requirements.txt
Labels: Level2, Approved, GSSoC22

#180 updated scroll bar
  assets/css/style.css
Labels: Approved, GSSoC22, Level0

#190 Combination Lock using Arduino #188
  Minor Scripts/Arduino/Combination Lock using Arduino/Combination_Lock_Using_Arduino.ino
  Minor Scripts/Arduino/Combination Lock using Arduino/Images/Circuit Diagram.png
  Minor Scripts/Arduino/Combination Lock using Arduino/Images/Combination_Lock_Using_Arduino_Simulation.mp4
  Minor Scripts/Arduino/Combination Lock using Arduino/README.md
  Minor Scripts/Arduino/Combination Lock using Arduino/Requirements.txt
Labels: Level2, Approved, GSSoC22

#161 overflow managed and cards section improved
  assets/css/style.css
  index.html
Labels: Level1, Approved, GSSoC22

#201 Obstacle Avoidance Game added
  Minor Scripts/Arduino/Obstacle Avoidance Game/Images/obstacle_avoidance_game.mp4
  Minor Scripts/Arduino/Obstacle Avoidance Game/Images/obstacle_avoidance_game.png
  Minor Scripts/Arduino/Obstacle Avoidance Game/README.md
  Minor Scripts/Arduino/Obstacle Avoidance Game/obstacle_avoidance_game.ino
  Minor Scripts/Arduino/Obstacle Avoidance Game/requirements.txt
Labels: Level3, Fix the Changes, GSSoC22

#189 Door Lock System using 8051 Microcontroller
  Minor Scripts/8051/Door Lock System/DoorLock.c
  Minor Scripts/8051/Door Lock System/Gallery/Doorlock_System-2022-04-07_19.32.21.mp4
  Minor Scripts/8051/Door Lock System/Gallery/doorlock1.PNG
  Minor Scripts/8051/Door Lock System/Gallery/doorlock2.PNG
  Minor Scripts/8051/Door Lock System/Gallery/doorlock3.PNG
  Minor Scripts/8051/Door Lock System/README.md
  Minor Scripts/8051/Door Lock System/design/Doorlocksys.pdsprj
  Minor Scripts/8051/Door Lock System/doorlc.hex
  Minor Scripts/8051/Door Lock System/requirements.txt
Labels: Level2, Approved, GSSoC22

#207 Pedestrian Traffic Signal System Using Arduino #206
  Minor Scripts/Arduino/Pedestrian Traffic Signal System using Arduino/Images/Circuit Diagram.png
  Minor Scripts/Arduino/Pedestrian Traffic Signal System using Arduino/Images/Pedestrian_Traffic_Signal_System_using_Arduino_Simulation_Video.mp4
  Minor Scripts/Arduino/Pedestrian Traffic Signal System using Arduino/Pedestrian_Traffic_Signal_System_using_Arduino.ino
  Minor Scripts/Arduino/Pedestrian Traffic Signal System using Arduino/README.md
  Minor Scripts/Arduino/Pedestrian Traffic Signal System using Arduino/Requirements.txt
Labels: Level2, Approved, GSSoC22

#208 Introduction to 8051 Microcontroller
  8051/Documentation/Introduction to 8051/README.md
Labels: Level2, Approved, GSSoC22
